name: Cypress Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        groups: [amazon, avenue] 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          start: yarn cypress run --env grepTags=@smoke 
          record: true
          parallel: true 
          spec: cypress/e2e/*/${{matrix.groups}}/*.cy.js
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_API_KEY: ${{ secrets.CYPRESS_API_KEY }}
      
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Screenshots
          path: cypress/screenshots
          retention-days: 1

      - name: Upload videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Videos
          path: cypress/videos
          retention-days: 1
